chore: Fix merge with WebKit
webkit submodule conflict cannot be resolved by git. Merging and Rebasing fail with:
```
error: Could not read c68a958a1865d6868b95ae53275d8f6e221a3315
fatal: revision walk setup failed
```